// agv-avf-runner — per-VM Apple Virtualization supervisor.
//
// This commit: control socket + JSON-RPC. The runner now binds a unix
// socket at the path supplied in the config and accepts line-delimited
// JSON commands (`stop`, `force_stop`, `status`). The Rust agv parent
// will use this to drive lifecycle without resorting to signals;
// signals still work as a fallback.

import AvfRunnerCore
import Foundation
import Virtualization
import Darwin

// ---------------------------------------------------------------------------
// JSON config sent by the Rust side
// ---------------------------------------------------------------------------

struct RunnerConfig: Codable {
    let name: String
    let memoryBytes: UInt64
    let cpuCount: Int
    let diskPath: String
    let seedIsoPath: String
    let efiVariableStorePath: String
    let serialLogPath: String
    let controlSocketPath: String
    /// Where suspend writes the VM's machine state, and where the
    /// runner reads it on resume. Always populated — even VMs that
    /// never suspend declare a slot so the wire shape stays uniform.
    let snapshotPath: String
    /// True when this boot should restore from `snapshotPath`
    /// rather than start fresh. Set by the Rust side when the user
    /// runs `agv resume`. Defaults to false so a missing key
    /// (older config) means cold boot.
    let restoreOnBoot: Bool?
    /// Sidecar file storing this VM's MAC address. On first boot
    /// the runner generates a locally-administered MAC and writes
    /// it here; on subsequent boots (including resume from a
    /// snapshot) the runner reads it back. Required for resume to
    /// work: `saveMachineStateTo` records the network device's MAC
    /// in the snapshot, and `restoreMachineStateFrom` fails with
    /// `VZErrorDomain Code=12 "permission denied"` if the new
    /// configuration's MAC differs.
    let macAddressPath: String
    /// Sidecar file storing this VM's
    /// `VZGenericMachineIdentifier.dataRepresentation`. Like the
    /// MAC, this is autogenerated on first boot and persisted so
    /// resume sees an identical platform identifier — restore
    /// fails with the same Code=12 if this drifts between save
    /// and load.
    let machineIdentifierPath: String
}

// ---------------------------------------------------------------------------
// Control-socket protocol (line-delimited JSON, one request per line)
// ---------------------------------------------------------------------------

/// Request shape on the control socket.
///
/// Only `op` is required today; future commands may add typed argument
/// payloads (e.g. snapshot names for suspend). Encode as snake_case so
/// the wire format matches what Rust serde produces by default.
struct ControlRequest: Codable {
    let op: String
}

/// Response shape on the control socket.
///
/// `ok` is the only mandatory field. `error` is set when `ok = false`.
/// For the `status` op, `state` and `guestIp` are populated; for other
/// ops they're `nil`.
struct ControlResponse: Codable {
    let ok: Bool
    var error: String? = nil
    var state: String? = nil
    var guestIp: String? = nil
}

/// VM state tracked by the runner and surfaced via `status` queries.
enum VMState: String {
    case starting
    case running
    case suspending
    case suspended
    case stopping
    case stopped
    case errored
}

// ---------------------------------------------------------------------------
// CLI entry
// ---------------------------------------------------------------------------

let version = "0.0.0"

let args = CommandLine.arguments
var configPath: String? = nil
var validateOnly = false

var i = 1
while i < args.count {
    let arg = args[i]
    switch arg {
    case "--version", "-V":
        print("agv-avf-runner \(version)")
        exit(0)
    case "--help", "-h":
        printHelp()
        exit(0)
    case "--config":
        guard i + 1 < args.count else {
            die("--config requires a path argument")
        }
        configPath = args[i + 1]
        i += 2
        continue
    case "--validate-only":
        validateOnly = true
        i += 1
        continue
    default:
        die("unrecognized argument '\(arg)'")
    }
}

guard let configPath else {
    die("missing required --config <path>")
}

let config: RunnerConfig
let vmConfig: VZVirtualMachineConfiguration
let macAddress: VZMACAddress
do {
    config = try loadConfig(from: configPath)
    let built = try buildVMConfiguration(from: config)
    vmConfig = built.configuration
    macAddress = built.macAddress
    try vmConfig.validate()
} catch {
    die("\(error)")
}

if validateOnly {
    print("agv-avf-runner: config validates for VM '\(config.name)'")
    exit(0)
}

let runner = VMRunner(
    configuration: vmConfig,
    vmName: config.name,
    macAddress: macAddress,
    snapshotPath: config.snapshotPath,
    restoreOnBoot: config.restoreOnBoot ?? false
)

// Bind the control socket before booting so the parent agv process can
// connect immediately. If this fails, treat it as fatal — there's no
// point booting a VM we can't control.
let controlServer = ControlServer(path: config.controlSocketPath, runner: runner)
do {
    try controlServer.start()
} catch {
    die("failed to bind control socket at \(config.controlSocketPath): \(error)")
}

let exitCode = runner.runUntilStopped()
controlServer.stop()
exit(exitCode)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func loadConfig(from path: String) throws -> RunnerConfig {
    let url = URL(fileURLWithPath: path)
    let data = try Data(contentsOf: url)
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    return try decoder.decode(RunnerConfig.self, from: data)
}

/// `buildVMConfiguration`'s return shape: the VZ config plus the MAC
/// it pins on the virtio-net device, so callers can use the MAC later
/// to look up the guest's DHCP-leased IP.
struct BuiltVMConfig {
    let configuration: VZVirtualMachineConfiguration
    let macAddress: VZMACAddress
}

func buildVMConfiguration(from config: RunnerConfig) throws -> BuiltVMConfig {
    let vm = VZVirtualMachineConfiguration()
    vm.cpuCount = config.cpuCount
    vm.memorySize = config.memoryBytes

    let platform = VZGenericPlatformConfiguration()
    platform.machineIdentifier = try loadOrCreateMachineIdentifier(at: config.machineIdentifierPath)
    vm.platform = platform

    let bootLoader = VZEFIBootLoader()
    let efiURL = URL(fileURLWithPath: config.efiVariableStorePath)
    let efiStore: VZEFIVariableStore
    if FileManager.default.fileExists(atPath: efiURL.path) {
        efiStore = VZEFIVariableStore(url: efiURL)
    } else {
        efiStore = try VZEFIVariableStore(creatingVariableStoreAt: efiURL)
    }
    bootLoader.variableStore = efiStore
    vm.bootLoader = bootLoader

    let diskURL = URL(fileURLWithPath: config.diskPath)
    // Explicit `.cached` + `.full` instead of the 2-arg initializer's
    // `.automatic` default. `.automatic` lets the host page cache
    // reorder/coalesce writes in ways the guest's ext4 journal
    // doesn't tolerate — we and several other AVF projects (Lima,
    // Tart, UTM) hit "EXT4-fs error: bad entry in directory" /
    // "Detected aborted journal" the first time the guest does
    // sustained small-file I/O (`apt-get install`, untar of a docker
    // image, etc.). Root-cause is upstream in AVF; the workaround is
    // well-trodden:
    //   * Lima PR #2026 (lima-vm/lima): switched to `.cached` after
    //     hourly corruption reports on Apple Silicon (issue #1957).
    //   * Tart `Sources/tart/VM.swift`: `.cached` for Linux guests,
    //     `.automatic` only for macOS guests.
    //   * UTM PR #5919 (utmapp/UTM): merged `.cached` + virtio-blk
    //     after testing `.uncached` and NVMe and finding cached
    //     virtio more reliable on Linux 6.1+.
    let diskAttachment = try VZDiskImageStorageDeviceAttachment(
        url: diskURL,
        readOnly: false,
        cachingMode: .cached,
        synchronizationMode: .full
    )
    let diskDevice = VZVirtioBlockDeviceConfiguration(attachment: diskAttachment)

    let seedURL = URL(fileURLWithPath: config.seedIsoPath)
    let seedAttachment = try VZDiskImageStorageDeviceAttachment(
        url: seedURL,
        readOnly: true
    )
    let seedDevice = VZVirtioBlockDeviceConfiguration(attachment: seedAttachment)

    vm.storageDevices = [diskDevice, seedDevice]

    // Pin a locally-administered MAC so we can look the guest up in
    // /var/db/dhcpd_leases later. Persisted via macAddressPath:
    // first boot generates + writes; subsequent boots read. This
    // is required for resume — `saveMachineStateTo` records the
    // MAC in the snapshot, and `restoreMachineStateFrom` rejects a
    // configuration whose MAC differs from the saved one
    // (Code=12 "permission denied" — Apple's error message is
    // unhelpful, but the cause is the device-config diff).
    let mac = try loadOrCreateMac(at: config.macAddressPath)
    let netDevice = VZVirtioNetworkDeviceConfiguration()
    netDevice.macAddress = mac
    netDevice.attachment = VZNATNetworkDeviceAttachment()
    vm.networkDevices = [netDevice]

    let serial = VZVirtioConsoleDeviceSerialPortConfiguration()
    let serialURL = URL(fileURLWithPath: config.serialLogPath)
    // Only create the file on cold boot — `restoreMachineStateFrom`
    // requires the new VZ configuration to match what was saved, and
    // truncating the serial log on resume seemed to be one of the
    // things AVF disliked (Code=12 "permission denied"). Append-only
    // on every boot keeps the device state stable from AVF's view.
    if !FileManager.default.fileExists(atPath: serialURL.path) {
        FileManager.default.createFile(atPath: serialURL.path, contents: nil, attributes: nil)
    }
    let serialHandle = try FileHandle(forWritingTo: serialURL)
    serialHandle.seekToEndOfFile()
    serial.attachment = VZFileHandleSerialPortAttachment(
        fileHandleForReading: nil,
        fileHandleForWriting: serialHandle
    )
    vm.serialPorts = [serial]

    // Intentionally NO entropy device: VZVirtioEntropyDeviceConfiguration
    // is incompatible with `saveMachineStateTo` / `restoreMachineStateFrom`
    // — leaving it in causes resume to fail with
    // `VZErrorDomain Code=12 "permission denied"` (Apple's error
    // message is misleading; it's actually a device-compatibility
    // mismatch). Documented by UTM and several other AVF wrappers.
    // Linux pulls entropy from many other sources (timer interrupts,
    // virtio activity, RDRAND on Apple Silicon's emulation layer),
    // so removing virtio-rng is benign for agent workloads. Users
    // with stricter RNG requirements (FIPS) should set
    // `backend = "qemu"`, which already supports explicit
    // virtio-rng wiring.

    return BuiltVMConfig(configuration: vm, macAddress: mac)
}

/// Read the persisted MAC from `path`, or generate + write a new
/// locally-administered one if the file doesn't exist. Idempotent —
/// once written, the MAC stays stable across runner restarts. Used
/// for stable guest networking and (more critically) for snapshot
/// resume to succeed: AVF's `restoreMachineStateFrom` requires the
/// new VM configuration's MAC to match the one saved with
/// `saveMachineStateTo`.
///
/// Format on disk: the canonical 6-byte colon-separated lowercase
/// hex form (what `VZMACAddress.string` produces).
/// Same shape as `loadOrCreateMac` but for
/// `VZGenericMachineIdentifier`. Stored as raw bytes
/// (its `dataRepresentation`); `init(dataRepresentation:)`
/// returns nil on malformed input.
func loadOrCreateMachineIdentifier(at path: String) throws -> VZGenericMachineIdentifier {
    let fm = FileManager.default
    if fm.fileExists(atPath: path) {
        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        guard let ident = VZGenericMachineIdentifier(dataRepresentation: data) else {
            throw NSError(
                domain: "agv-avf-runner.machine-id",
                code: 1,
                userInfo: [
                    NSLocalizedDescriptionKey:
                        "malformed VZGenericMachineIdentifier at \(path)"
                ]
            )
        }
        return ident
    }
    let ident = VZGenericMachineIdentifier()
    try ident.dataRepresentation.write(to: URL(fileURLWithPath: path))
    return ident
}

func loadOrCreateMac(at path: String) throws -> VZMACAddress {
    let fm = FileManager.default
    if fm.fileExists(atPath: path) {
        let raw = try String(contentsOfFile: path, encoding: .utf8)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard let mac = VZMACAddress(string: raw) else {
            throw NSError(
                domain: "agv-avf-runner.mac",
                code: 1,
                userInfo: [
                    NSLocalizedDescriptionKey:
                        "malformed MAC at \(path): \(raw)"
                ]
            )
        }
        return mac
    }
    let mac = VZMACAddress.randomLocallyAdministered()
    try mac.string.write(toFile: path, atomically: true, encoding: .utf8)
    return mac
}

func printHelp(to handle: FileHandle = FileHandle.standardOutput) {
    let lines = [
        "agv-avf-runner — Apple Virtualization supervisor for agv VMs",
        "",
        "Usage:",
        "  agv-avf-runner --config <path>            Boot a VM",
        "  agv-avf-runner --config <path> --validate-only",
        "                                            Validate config without booting",
        "  agv-avf-runner --version                  Print version",
        "  agv-avf-runner --help                     Print this help",
        "",
        "The runner is normally spawned by the agv Rust binary; manual",
        "invocation is intended for development and config validation.",
        "",
    ].joined(separator: "\n")
    handle.write(Data(lines.utf8))
}

func die(_ msg: String) -> Never {
    FileHandle.standardError.write(Data("agv-avf-runner: \(msg)\n".utf8))
    exit(2)
}

// ---------------------------------------------------------------------------
// VM runner: boot the configured VM and block until it stops.
// ---------------------------------------------------------------------------

final class VMRunner: NSObject, VZVirtualMachineDelegate {
    let vmName: String
    /// MAC pinned on the guest's virtio-net device. Used for DHCP
    /// lease lookup when `status` queries arrive.
    let macAddress: VZMACAddress
    /// Where to write the machine state on suspend, and where to
    /// read it from on restore. Identical path; the `restoreOnBoot`
    /// flag picks the direction at startup.
    let snapshotPath: String
    let restoreOnBoot: Bool
    private let queue: DispatchQueue
    private let vm: VZVirtualMachine
    private let exitSemaphore = DispatchSemaphore(value: 0)
    private var exitCode: Int32 = 0
    private var hasExited = false

    /// Coarse-grained VM state tracked for `status` queries. Updated
    /// from the VM queue and from the start completion handler; read
    /// from the control queue under `stateLock`.
    private var _state: VMState = .starting
    private let stateLock = NSLock()

    init(
        configuration: VZVirtualMachineConfiguration,
        vmName: String,
        macAddress: VZMACAddress,
        snapshotPath: String,
        restoreOnBoot: Bool
    ) {
        self.vmName = vmName
        self.macAddress = macAddress
        self.snapshotPath = snapshotPath
        self.restoreOnBoot = restoreOnBoot
        self.queue = DispatchQueue(label: "agv-avf-runner.vm.\(vmName)")
        self.vm = VZVirtualMachine(configuration: configuration, queue: self.queue)
        super.init()
        queue.sync {
            self.vm.delegate = self
        }
    }

    var state: VMState {
        stateLock.lock()
        defer { stateLock.unlock() }
        return _state
    }

    private func setState(_ new: VMState) {
        stateLock.lock()
        _state = new
        stateLock.unlock()
    }

    func runUntilStopped() -> Int32 {
        let signalSources = installSignalHandlers()
        defer { for s in signalSources { s.cancel() } }

        if restoreOnBoot {
            queue.async { [weak self] in
                self?.restoreAndResume()
            }
        } else {
            queue.async { [weak self] in
                guard let self else { return }
                self.vm.start { [weak self] result in
                    guard let self else { return }
                    switch result {
                    case .success:
                        self.setState(.running)
                    case .failure(let err):
                        FileHandle.standardError.write(
                            Data("agv-avf-runner: VM '\(self.vmName)' failed to start: \(err)\n".utf8)
                        )
                        self.setState(.errored)
                        self.exitCode = 1
                        self.signalExitOnce()
                    }
                }
            }
        }

        exitSemaphore.wait()
        return exitCode
    }

    /// Restore the VM state from `snapshotPath` and resume execution.
    /// Called instead of `vm.start(...)` when `restoreOnBoot` is true
    /// (the Rust side sets this on `agv resume`).
    ///
    /// On any failure (corrupt snapshot, version mismatch, missing
    /// file) we surface the error to stderr and exit with code 1 —
    /// the parent treats that as a failed resume and the user can
    /// fall back to a cold start. We do NOT silently fall back to
    /// `vm.start` because that would lose the in-RAM guest state
    /// the user expected to recover.
    private func restoreAndResume() {
        let url = URL(fileURLWithPath: snapshotPath)
        vm.restoreMachineStateFrom(url: url) { [weak self] error in
            guard let self else { return }
            if let error {
                FileHandle.standardError.write(
                    Data("agv-avf-runner: restoreMachineStateFrom failed for '\(self.vmName)': \(error)\n".utf8)
                )
                self.setState(.errored)
                self.exitCode = 1
                self.signalExitOnce()
                return
            }
            self.vm.resume { [weak self] result in
                guard let self else { return }
                switch result {
                case .success:
                    self.setState(.running)
                    // Snapshot has served its purpose. Remove so the
                    // file isn't mistakenly reused next boot and to
                    // free disk (snapshot ≈ RAM size).
                    try? FileManager.default.removeItem(atPath: self.snapshotPath)
                case .failure(let err):
                    FileHandle.standardError.write(
                        Data("agv-avf-runner: vm.resume failed for '\(self.vmName)': \(err)\n".utf8)
                    )
                    self.setState(.errored)
                    self.exitCode = 1
                    self.signalExitOnce()
                }
            }
        }
    }

    /// Pause the VM, write its full state to `snapshotPath`, then
    /// exit cleanly. The Rust side observes our exit (PID gone +
    /// socket removed) to know the suspend is complete.
    ///
    /// Failure modes:
    /// - `pause` fails → leave VM running, surface error to stderr.
    ///   No exit; the user can retry or fall back to `agv stop`.
    /// - `saveMachineStateTo` fails → resume the VM so we don't
    ///   leave it wedged in pause, surface the error. The on-disk
    ///   snapshot is removed if a partial write occurred (the
    ///   library may or may not clean up; defensive).
    func requestSuspend() {
        queue.async { [weak self] in
            guard let self else { return }
            if self.hasExited { return }
            self.setState(.suspending)
            self.vm.pause { [weak self] result in
                guard let self else { return }
                if case .failure(let err) = result {
                    FileHandle.standardError.write(
                        Data("agv-avf-runner: pause failed for '\(self.vmName)': \(err)\n".utf8)
                    )
                    // Revert to running state — VM is still alive.
                    self.setState(.running)
                    return
                }
                let url = URL(fileURLWithPath: self.snapshotPath)
                self.vm.saveMachineStateTo(url: url) { [weak self] err in
                    guard let self else { return }
                    if let err {
                        FileHandle.standardError.write(
                            Data("agv-avf-runner: saveMachineStateTo failed for '\(self.vmName)': \(err)\n".utf8)
                        )
                        // Best-effort cleanup of a potentially partial file.
                        try? FileManager.default.removeItem(atPath: self.snapshotPath)
                        // Resume so we don't leave the VM paused.
                        self.vm.resume { _ in
                            self.setState(.running)
                        }
                        return
                    }
                    self.setState(.suspended)
                    self.signalExitOnce()
                }
            }
        }
    }

    private func installSignalHandlers() -> [DispatchSourceSignal] {
        var sources: [DispatchSourceSignal] = []
        for sig in [SIGTERM, SIGINT] {
            signal(sig, SIG_IGN)
            let src = DispatchSource.makeSignalSource(
                signal: sig,
                queue: DispatchQueue.global()
            )
            src.setEventHandler { [weak self] in
                self?.requestGracefulStop()
            }
            src.resume()
            sources.append(src)
        }
        return sources
    }

    func requestGracefulStop() {
        queue.async { [weak self] in
            guard let self else { return }
            if self.hasExited { return }
            self.setState(.stopping)
            do {
                try self.vm.requestStop()
            } catch {
                FileHandle.standardError.write(
                    Data("agv-avf-runner: requestStop failed for '\(self.vmName)': \(error); forcing stop\n".utf8)
                )
                self.vm.stop { _ in
                    self.signalExitOnce()
                }
            }
        }
    }

    func forceStop() {
        queue.async { [weak self] in
            guard let self else { return }
            if self.hasExited { return }
            self.setState(.stopping)
            self.vm.stop { _ in
                self.signalExitOnce()
            }
        }
    }

    private func signalExitOnce() {
        if hasExited { return }
        hasExited = true
        // Preserve `.errored` and `.suspended` — both convey
        // important information to the parent (errored = failure,
        // suspended = state-on-disk waiting for resume). Otherwise
        // we record the stop.
        let current = state
        if current != .errored && current != .suspended {
            setState(.stopped)
        }
        exitSemaphore.signal()
    }

    // MARK: - VZVirtualMachineDelegate

    func guestDidStop(_ virtualMachine: VZVirtualMachine) {
        signalExitOnce()
    }

    func virtualMachine(_ virtualMachine: VZVirtualMachine, didStopWithError error: Error) {
        FileHandle.standardError.write(
            Data("agv-avf-runner: VM '\(vmName)' stopped with error: \(error)\n".utf8)
        )
        setState(.errored)
        exitCode = 1
        signalExitOnce()
    }
}

// ---------------------------------------------------------------------------
// Control server: unix-socket JSON-RPC for parent-process control.
// ---------------------------------------------------------------------------

/// Per-VM JSON-RPC server bound to the unix socket the parent (Rust
/// agv) uses to drive lifecycle. Each connection is one-shot: read one
/// line of JSON, write one line back, close.
///
/// Why a fresh connection per command rather than a long-lived one:
/// matches the call sites on the parent side (each `agv stop` /
/// `agv ssh` reads-modifies-state independently) and keeps the
/// protocol stateless. The runner stays running across many
/// connections until the VM exits (signal, `stop` op, or guest
/// shutdown).
final class ControlServer {
    private let path: String
    private let runner: VMRunner
    private let queue: DispatchQueue
    private var fd: Int32 = -1
    private var listenSource: DispatchSourceRead?

    init(path: String, runner: VMRunner) {
        self.path = path
        self.runner = runner
        self.queue = DispatchQueue(label: "agv-avf-runner.control.\(runner.vmName)")
    }

    func start() throws {
        // Clean up a stale socket from a previous unclean exit.
        unlink(path)

        fd = socket(AF_UNIX, SOCK_STREAM, 0)
        guard fd >= 0 else {
            throw posixError("socket", errno)
        }

        var addr = sockaddr_un()
        addr.sun_family = sa_family_t(AF_UNIX)
        let pathMaxLen = MemoryLayout.size(ofValue: addr.sun_path) - 1
        let pathBytes = Array(path.utf8)
        guard pathBytes.count <= pathMaxLen else {
            Darwin.close(fd)
            fd = -1
            throw posixError("socket path too long (\(pathBytes.count) > \(pathMaxLen))", EINVAL)
        }
        withUnsafeMutablePointer(to: &addr.sun_path) { ptr in
            ptr.withMemoryRebound(to: UInt8.self, capacity: pathMaxLen + 1) { dst in
                _ = pathBytes.withUnsafeBufferPointer { src in
                    memcpy(dst, src.baseAddress, src.count)
                }
                dst[pathBytes.count] = 0
            }
        }

        let addrLen = socklen_t(MemoryLayout<sockaddr_un>.size)
        let bindRet = withUnsafePointer(to: &addr) { addrPtr in
            addrPtr.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockPtr in
                bind(fd, sockPtr, addrLen)
            }
        }
        guard bindRet == 0 else {
            let err = errno
            Darwin.close(fd)
            fd = -1
            throw posixError("bind", err)
        }

        // Tighten permissions: only the owner of the agv data dir
        // should be able to control the VM.
        chmod(path, 0o600)

        guard listen(fd, 4) == 0 else {
            let err = errno
            Darwin.close(fd)
            fd = -1
            throw posixError("listen", err)
        }

        let src = DispatchSource.makeReadSource(fileDescriptor: fd, queue: queue)
        src.setEventHandler { [weak self] in
            self?.acceptOne()
        }
        src.resume()
        listenSource = src
    }

    func stop() {
        listenSource?.cancel()
        listenSource = nil
        if fd >= 0 {
            Darwin.close(fd)
            fd = -1
        }
        unlink(path)
    }

    private func acceptOne() {
        var clientAddr = sockaddr_un()
        var clientAddrLen = socklen_t(MemoryLayout<sockaddr_un>.size)
        let clientFd = withUnsafeMutablePointer(to: &clientAddr) { addrPtr in
            addrPtr.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockPtr in
                accept(fd, sockPtr, &clientAddrLen)
            }
        }
        guard clientFd >= 0 else { return }
        // Handle on the same queue — connections are short-lived; one
        // command, one response, close. No need for a worker pool.
        queue.async { [weak self] in
            self?.handleClient(clientFd)
        }
    }

    private func handleClient(_ clientFd: Int32) {
        defer { Darwin.close(clientFd) }
        guard let line = readLine(from: clientFd) else { return }

        let response: ControlResponse
        do {
            let req = try JSONDecoder().decode(ControlRequest.self, from: Data(line.utf8))
            response = dispatch(req)
        } catch {
            response = ControlResponse(ok: false, error: "invalid request: \(error)")
        }
        writeResponse(clientFd, response)
    }

    private func dispatch(_ req: ControlRequest) -> ControlResponse {
        switch req.op {
        case "stop":
            runner.requestGracefulStop()
            return ControlResponse(ok: true)
        case "force_stop":
            runner.forceStop()
            return ControlResponse(ok: true)
        case "suspend":
            runner.requestSuspend()
            return ControlResponse(ok: true)
        case "status":
            // Look up the guest IP fresh on every status — DHCP
            // leases can take a few seconds after boot, and a stale
            // cached value would mislead the parent. Hostname-keyed
            // primarily (set via cloud-init's `local-hostname` to
            // match the VM name); MAC as fallback.
            let ip = LeaseLookup.findGuestIp(
                hostname: runner.vmName,
                mac: runner.macAddress.string
            )
            return ControlResponse(
                ok: true,
                state: runner.state.rawValue,
                guestIp: ip
            )
        default:
            return ControlResponse(ok: false, error: "unknown op '\(req.op)'")
        }
    }

    private func readLine(from fd: Int32) -> String? {
        // 4 KiB ceiling — protocol messages are tiny; anything bigger
        // is malformed input or an attack.
        var buf = [UInt8]()
        buf.reserveCapacity(256)
        var b: UInt8 = 0
        while buf.count < 4096 {
            let n = read(fd, &b, 1)
            if n != 1 { break }
            if b == 0x0a { break } // \n
            buf.append(b)
        }
        return String(bytes: buf, encoding: .utf8)
    }

    private func writeResponse(_ fd: Int32, _ response: ControlResponse) {
        let encoder = JSONEncoder()
        encoder.keyEncodingStrategy = .convertToSnakeCase
        guard var data = (try? encoder.encode(response)) else { return }
        data.append(0x0a)
        data.withUnsafeBytes { ptr in
            _ = write(fd, ptr.baseAddress, ptr.count)
        }
    }

    private func posixError(_ op: String, _ code: Int32) -> NSError {
        let msg = String(cString: strerror(code))
        return NSError(
            domain: "agv-avf-runner.control",
            code: Int(code),
            userInfo: [NSLocalizedDescriptionKey: "\(op): \(msg)"]
        )
    }
}
